### ISSUE TITLE
Random SIGSEGV

### ISSUE THREAD

**Issue by K0nfy** [mertushka/haxball.js#23]
This problem is old, and I don't really want to investigate it and try some time consuming things to fix it because I'm not really bothered of it. 

Around a half of a year ago I've launched a room with the `haxball.js` under the hood and the app was crashing randomly, and some time later I've noticed by accident the "SIGSEGV" error inside a logs of my apps launcher, `pm2`. 
Specifically:
`"/home/username/.pm2/pm2.log"`
`2023-02-25T18:07:02: PM2 log: App [hax-host:4] exited with code [0] via signal [SIGSEGV]`

Then from [this article](https://httptoolkit.com/blog/how-to-debug-node-segfaults/#how-can-i-fix-it) I've found the problem is probably because of [this module](https://github.com/koush/node-webrtc) that is being used by `haxball.js`, and since I was using `nodejs v16` I've switched to `nodejs v14` because it's listed [here](https://github.com/koush/node-webrtc#supported-platforms). Sadly this did not fix the problem, but it seems to be better

Approximately, with a `nodejs 16.15.0` I had 4 crashes in 4 months, and with a `nodejs 14.21.3` I had 2 crashes in 3.5 months. The crashes are seems to be happening only when the room is being played, not when the room is empty. 
The room activity, approximately, is 10+ people, 6+ hours a day, and the last months activity is definitely higher than it was in first months, so I guess if I'll switch back to `node v16` I'll probably get more crashes than it was when there was less activity. Maybe, or maybe not, idk

I think that I could try to use another versions of node, or maybe try another JavaScript runtimes (deno, bun), or another linux build or distribution, but this crashes are so rare, this might take a years to debug this problem in that way. The problem is still annoying though

`cat /etc/os-release` output:
```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
```

**Comment by mertushka** [comment]
This bug may have been fixed in `v2.2.0`. Closing as solved for now, follow-up needed.

**Comment by K0nfy** [comment]
I'll test it. I still have the same project thus still have the problem. I've attached a log below where you can see the app launch times that precedes the crashes and their frequency. I believe these are all of the crashes I've had. I also forgot to mention that after an every crash I also have a core dump file generated that could potentially be analyzed to find the problem. I'm just not sure what data is in there and how sensitive it is to share it. But since there is a new version to test I think it is not that important for now. 

```
2023-02-23 23:10:13: PM2 log: App [hax-host:4] online
2023-02-25 18:07:02: PM2 log: App [hax-host:4] exited with code [0] via signal [SIGSEGV]

2023-03-17 02:30:50: PM2 log: App [hax-host:4] online
2023-03-17 22:00:11: PM2 log: App [hax-host:4] exited with code [0] via signal [SIGSEGV]

2023-03-18 15:38:23: PM2 log: App [hax-host:4] online
2023-03-23 17:11:37: PM2 log: App [hax-host:4] exited with code [0] via signal [SIGSEGV]

2023-05-26 12:01:04: PM2 log: App [hax-host:4] online
2023-05-31 17:44:10: PM2 log: App [hax-host:4] exited with code [0] via signal [SIGSEGV]

2023-06-09 23:18:59: PM2 log: App [hax-host:1] online
2023-06-17 18:09:31: PM2 log: App [hax-host:1] exited with code [0] via signal [SIGSEGV]

2023-09-01 07:02:10: PM2 log: App [hax-host:3] online
2023-09-11 09:58:53: PM2 log: App [hax-host:3] exited with code [0] via signal [SIGSEGV]

2024-02-08 04:17:21: PM2 log: App [hax-host:7] online
2024-02-08 15:13:44: PM2 log: App [hax-host:7] exited with code [0] via signal [SIGSEGV]

2024-03-27 15:19:40: PM2 log: App [hax-host:3] online
2024-04-08 17:39:47: PM2 log: App [hax-host:3] exited with code [0] via signal [SIGSEGV]

2024-04-28 21:33:44: PM2 log: App [hax-host:3] online
2024-05-01 08:19:20: PM2 log: App [hax-host:3] exited with code [0] via signal [SIGSEGV]

2024-05-28 13:10:38: PM2 log: App [hax-host:3] online
2024-06-17 18:21:38: PM2 log: App [hax-host:3] exited with code [0] via signal [SIGSEGV]

2024-06-17 21:05:19: PM2 log: App [hax-host:3] online
2024-07-27 23:51:05: PM2 log: App [hax-host:3] exited with code [0] via signal [SIGSEGV]
```
 
p.s. The app is up 24/7 and there are still around the same amount of players

**Comment by K0nfy** [comment]
Nevermind, I'm not going to test it right now. With the new version I've got [this issue](https://github.com/WonderInventions/node-webrtc/issues/4) which I couldn't fix in an easy way. This issue makes `haxball.js` completely broken. I don't want to deal with this anymore

**Comment by K0nfy** [comment]
Issue with a non working haxball.js 2.2.0 doesn't appear in Ubuntu 22.04.3

**Comment by mertushka** [comment]
@K0nfy You can check #38 if you are still interested.

**Comment by K0nfy** [comment]
I left haxball for now. Room works but it is not being updated. If something would need to get changed I might give this a try
